{% set name = "serialite" %}
{% set version = "0.3.6" %}
{% set python_min = "3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/serialite-{{ version }}.tar.gz
  sha256: b2e97caa5832325703950d0afbedbc1cddd681ae4d5db4be88ca87dc04c7d8ce

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - uv-build >=0.8,<0.9
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - typing_extensions >=4.3.0,<5.0.0
  run_constrained:
    - fastapi >=0.100.0,<0.111.0
    - pydantic >=1.10.0,<2.0.0
    - ordered-set >=4.1.0,<5.0.0
    - numpy >=1.25.0,<3.0.0

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - serialite
  commands:
    - pip check

about:
  home: https://github.com/drhagen/serialite/
  summary: A serialization library for Python
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/drhagen/serialite/

extra:
  recipe-maintainers:
    - drhagen
