{% set name = "serialite" %}
{% set version = "0.5.1" %}
{% set python_min = "3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/serialite-{{ version }}.tar.gz
  sha256: c54c4992aa8e8ded15a7eea465871f44847e532e97dce337057207dee1b9e6ba

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - uv-build >=0.9,<0.10
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - returns >=0.20,<0.27
  run_constrained:
    - fastapi >=0.121.0,<0.122.0
    - pydantic >=2.0.0,<3.0.0
    - ordered-set >=4.1.0,<5.0.0
    - numpy >=1.25.0,<3.0.0

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - serialite
  commands:
    - pip check

about:
  home: https://github.com/drhagen/serialite/
  summary: A serialization library for Python
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/drhagen/serialite/

extra:
  recipe-maintainers:
    - drhagen
