{% set name = "serialite" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/serialite-{{ version }}.tar.gz
  sha256: 9cdf926b5f829526353434789aaa0f509593caa8ddb292be88f419dc16d95945

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.10.0,<4.0.0
    - typing_extensions >=4.3.0,<5.0.0
  run_constrained:
    - fastapi >=0.100.0,<0.101.0
    - pydantic >=1.10.0,<2.0.0
    - ordered-set >=4.1.0,<5.0.0
    - numpy >=1.25.0,<2.0.0

test:
  requires:
    - pip
  imports:
    - serialite
  commands:
    - pip check

about:
  home: https://github.com/drhagen/serialite/
  summary: A serialization library for Python
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/drhagen/serialite/

extra:
  recipe-maintainers:
    - drhagen
